[logging]
workflow_level = 'INFO'
utils_level = 'INFO'
interface_level = 'INFO'
log_to_file = false
log_directory = 0
log_size = 16384000
log_rotate = 4

[execution]
create_report = true
crashdump_dir = 0
hash_method = 'timestamp'
job_finished_timeout = 5
keep_inputs = false
local_hash_check = true
matplotlib_backend = 'Agg'
plugin = 'Linear'
remove_node_directories = false
remove_unnecessary_outputs = true
try_hard_link_datasink = true
single_thread_matlab = true
crashfile_format = 'pklz'
stop_on_first_crash = false
stop_on_first_rerun = false
use_relative_paths = false
stop_on_unknown_version = false
write_provenance = false
parameterize_dirs = true
poll_sleep_duration = 2
xvfb_max_wait = 10
check_version = true

[monitoring]
enabled = false
sample_frequency = 1
summary_append = true

[check]
interval = 1209600
